import sys
import colorama
from colorama import Fore
import re

from codes.printer import Printer
from codes.setvars import SetVars
from codes.printvar import PrintVar
from codes.inputtovar import Input
from codes.mathcmd import MathCmd
from codes.compline import CompLine
from codes.delaycmd import Delay
from codes.ifcmd import IfCmd
from codes.runifcmd import RunIfCmd
from codes.exitcmd import ExitCmd
from codes.importcmd import ImportCmd
from codes.passcmd import PassCmd
import varmanager
import commands


def toC(commandsList):
    
    for cc in commandsList:
        
        if type(cc) == ImportCmd:

            try:

                cc.loadFile()
                cc.addToCommandList()

            except:

                print(f"{Fore.RED}\nError!!!{Fore.WHITE}\n")
                sys.exit(0)
        
    
    with open("output.c", "w") as f:
        
        f.write(toCFullText(commandsList))
        
    

def toCFullText(commandsList):
    
    print(f'{Fore.GREEN}Ignore all text in magenta!{Fore.MAGENTA}')

    output = "// Generated by LUC https://github.com/Rahonn/luc\n"

    output += f'#include <stdio.h>\n#include <string.h>\n#include <stdlib.h>\n'
    
    mathcmdU = False
    ifcmdU = False
    
    for i in commandsList:

        if type(i) == MathCmd:

            output += f'#include <math.h>\n#include <time.h>\n'
            mathcmdU = True
            break
        
    for i in commandsList:

        if type(i) == IfCmd:

            ifcmdU = True
            break
        
    for i in commandsList:

        if type(i) == Delay:

            output += f'#ifdef _WIN32\n\t#include <windows.h>\n\tvoid sleepfunLUC(unsigned int millis) {{\n\t\tSleep(millis);\n\t}}\n#else\n\t#include <unistd.h>\n\tvoid sleepfunLUC(unsigned int millis) {{\n\t\tusleep(millis * 1000);\n\t}}\n#endif\n'
            break
        
    output += f'int main() {{\nconst char VERSION[] = "{varmanager.vars["VERSION"]}";\n'
    
    if mathcmdU:
        
        output += 'char *eptr;\nsrand(time(0));\n'
        
    if ifcmdU and not mathcmdU:
        
        output += 'char *eptr;\n'
        
    output += toCText(commandsList)

    output = f"{output}return 0;\n}}"
        
    print(Fore.RESET)
    
    return output


def toCText(commandsList):

    output = ""

    mathcmdU = False
    ifcmdU = False

    for cc in commandsList:

        if type(cc) == Printer:

            output += f'printf("{cc.get_data()["text"]}\\n");\n'

        if type(cc) == SetVars:

            if not cc.run():

                print(f"{Fore.RED}\nError!!!{Fore.WHITE}\n")
                sys.exit(0)

            data = cc.get_data()

            if data["new"] == True:

                output += f'char {data["name"]}[] = "{data["value"]}";\n'

            else:

                output += f'strcpy({data["name"]}, "{data["value"]}");\n'

        if type(cc) == Input:

            if varmanager.vars.get(cc.get_data()["varname"]) is None:

                output += f'char {cc.get_data()["varname"]}[50];\n'
                output += f'fgets({cc.get_data()["varname"]}, 50, stdin);\n'

                varmanager.vars[cc.get_data()["varname"]] = "1"

            else:

                print(f"{Fore.RED}\nError!!!{Fore.WHITE}\n")
                sys.exit(0)

        if type(cc) == PrintVar:

            output += f'printf("%s\\n", {cc.get_data()["varName"]});\n'

        if type(cc) == MathCmd:

            num1 = cc.get_data()["val1"]
            num2 = cc.get_data()["val2"]

            if not re.search(r"[0-9]", num1):

                num1 = f"strtod({num1}, &eptr)"

            if not re.search(r"[0-9]", num2):

                num2 = f"strtod({num2}, &eptr)"

            if varmanager.vars.get(cc.get_data()["varname"]) is None:

                varmanager.vars[cc.get_data()["varname"]] = True

                if cc.get_data()["op"] == "**":

                    output += f'char {cc.get_data()["varname"]}[50];\nsnprintf({cc.get_data()["varname"]}, 50, \"%lf\", pow({num1}, {num2}));\n'

                elif cc.get_data()["op"] == "RAND" and cc.get_data()["val1"] == "@" and cc.get_data()["val2"] == "@":

                    output += f'char {cc.get_data()["varname"]}[50];\nsnprintf({cc.get_data()["varname"]}, 50, \"%d\", rand());\n'

                elif cc.get_data()["op"] == "RAND" and not cc.get_data()["val1"] == "@" and not cc.get_data()["val2"] == "@":

                    output += f'char {cc.get_data()["varname"]}[50];\nsnprintf({cc.get_data()["varname"]}, 50, \"%d\", ((int) rand() % (int) {num2}) + (int) {num1});\n'

                else:

                    output += f'char {cc.get_data()["varname"]}[50];\nsnprintf({cc.get_data()["varname"]}, 50, \"%lf\", {num1} {cc.get_data()["op"]} {num2});\n'

            else:

                print(f"{Fore.RED}\nError!!!{Fore.WHITE}\n")
                sys.exit(0)

        if type(cc) == Delay:

            data = cc.get_data()

            output += f'sleepfunLUC({int(float(data["time"]) * 1000)});\n'

        if type(cc) == CompLine:

            output += f'{cc.get_data()["code"]}\n'

        if type(cc) == IfCmd:

            data = cc.get_data()

            if not cc.run():

                print(f"{Fore.RED}\nError!!!{Fore.WHITE}\n")
                sys.exit(0)

            newdata = cc.get_data()

            trueArg1STR = False

            if not re.search(r"^[0-9]+$|^[0-9]+\.[0-9]+", str(newdata["arg1isStr"])):

                trueArg1STR = True

            trueArg2STR = False

            if not re.search(r"^[0-9]+$|^[0-9]+\.[0-9]+", str(newdata["arg2isStr"])):

                trueArg2STR = True

            if not (data["op"] == "==" and ((data["arg1isVar"] and trueArg1STR) or data["arg1isStr"]) and ((data["arg2isVar"] and trueArg2STR) or data["arg2isStr"])):

                output += f'char {data["varname"]}[50];\nif ('

                if data["arg1isVar"]:

                    if not newdata["arg1isNum"]:

                        output += f'{data["arg1"][1::]}'

                    else:

                        output += f'strtod({data["arg1"][1::]}, &eptr)'

                if data["arg1isStr"]:

                    output += f'"{data["arg1"][1::][:-1]}"'

                if data["arg1isNum"]:

                    output += f'{data["arg1"]}'

                output += f' {data["op"]} '

                if data["arg2isVar"]:

                    if not newdata["arg2isNum"]:

                        output += f'{data["arg2"][1::]}'

                    else:

                        output += f'strtod({data["arg2"][1::]}, &eptr)'

                if data["arg2isStr"]:

                    output += f'"{data["arg2"][1::][:-1]}"'

                if data["arg2isNum"]:

                    output += f'{data["arg2"]}'

                output += ") {\n"
                output += f'strcpy({data["varname"]}, "{data["iftrue"]}");\n}}\nelse\n{{\nstrcpy({data["varname"]}, "{data["iffalse"]}");\n}}\n'

            else:

                output += f'char {data["varname"]}[50];\nif (strcmp('

                if data["arg1isVar"]:

                    output += f'{data["arg1"][1:]}'

                if data["arg1isStr"]:

                    output += f'"{data["arg1"][1:][:-1]}\\n"'

                if data["arg1isNum"]:

                    output += f'{data["arg1"]}'

                output += ","

                if data["arg2isVar"]:

                    output += f'{data["arg2"][1:]}'

                if data["arg2isStr"]:

                    output += f'"{data["arg2"][1:][:-1]}\\n"'

                if data["arg2isNum"]:

                    output += f'{data["arg2"]}'

                output += ") == 0) {\n"
                output += f'strcpy({data["varname"]}, "{data["iftrue"]}");\n}}\nelse\n{{\nstrcpy({data["varname"]}, "{data["iffalse"]}");\n}}\n'
        
        if type(cc) == RunIfCmd:

            data = cc.get_data()

            if not cc.run():

                print(f"{Fore.RED}\nError!!!{Fore.WHITE}\n")
                sys.exit(0)

            newdata = cc.get_data()

            trueArg1STR = False

            if not re.search(r"^[0-9]+$|^[0-9]+\.[0-9]+", str(newdata["arg1isStr"])):

                trueArg1STR = True

            trueArg2STR = False

            if not re.search(r"^[0-9]+$|^[0-9]+\.[0-9]+", str(newdata["arg2isStr"])):

                trueArg2STR = True

            if not (data["op"] == "==" and ((data["arg1isVar"] and trueArg1STR) or data["arg1isStr"]) and ((data["arg2isVar"] and trueArg2STR) or data["arg2isStr"])):

                output += 'if ('

                if data["arg1isVar"]:

                    if not newdata["arg1isNum"]:

                        output += f'{data["arg1"][1::]}'

                    else:

                        output += f'strtod({data["arg1"][1::]}, &eptr)'

                if data["arg1isStr"]:

                    output += f'"{data["arg1"][1::][:-1]}"'

                if data["arg1isNum"]:

                    output += f'{data["arg1"]}'

                output += f' {data["op"]} '

                if data["arg2isVar"]:

                    if not newdata["arg2isNum"]:

                        output += f'{data["arg2"][1::]}'

                    else:

                        output += f'strtod({data["arg2"][1::]}, &eptr)'

                if data["arg2isStr"]:

                    output += f'"{data["arg2"][1::][:-1]}"'

                if data["arg2isNum"]:

                    output += f'{data["arg2"]}'

                output += ") {\n"
                output += f'{toCText([commands.getCommand(data["iftrue"])])}\n}}\nelse\n{{\n{toCText([commands.getCommand(data["iffalse"])])}\n}}\n'

            else:

                output += f'if (strcmp('

                if data["arg1isVar"]:

                    output += f'{data["arg1"][1:]}'

                if data["arg1isStr"]:

                    output += f'"{data["arg1"][1:][:-1]}\\n"'

                if data["arg1isNum"]:

                    output += f'{data["arg1"]}'

                output += ","

                if data["arg2isVar"]:

                    output += f'{data["arg2"][1:]}'

                if data["arg2isStr"]:

                    output += f'"{data["arg2"][1:][:-1]}\\n"'

                if data["arg2isNum"]:

                    output += f'{data["arg2"]}'

                output += ") == 0) {\n"
                output += f'{toCText([commands.getCommand(data["iftrue"])])}\n}}\nelse\n{{\n{toCText([commands.getCommand(data["iffalse"])])}\n}}\n'
                
        if type(cc) == ExitCmd:
            
            output += "return 0;"
            
        if type(cc) == PassCmd:
            
            output += "{};"
            
    return output
